                   <!-- start footer-->
      </div>
    </div>
    <div class="clear">
      <hr/>
    </div>
    <div id="footer">
      <div class="footerelmt"> &copy gisgraphy 2014  | Logo by <a href="http://www.icondrawer.com/">icondrawer</a> | <a href="mailto:davidmasclet@gisgraphy.com">Contact</a> | <a href="http://davidmasclet.gisgraphy.com">Blog</a> (in french) </div>
<br/>
      <div class="clear">
        <hr/>
      </div>
      <div id="logos">
		<span class="license">Copyrights : Data © OpenStreetMap contributors, <a href="http://www.openstreetmap.org/copyright" target="license">ODbL 1.0</a> | Geonames : <a href="http://creativecommons.org/licenses/by/3.0/" target="license">Creative Commons Attribution 3.0 License</a> | Includes data from <a href="https://github.com/foursquare/quattroshapes/blob/master/LICENSE.md">foursquare quattroshapes</a></span>

	</div>
    </div>

<div id="feedback-box">
<a id="feedback" title="Please give us some feedbacks" href="http://www.gisgraphy.com/feedback/">
<img class="feedback" width="81" height="81" border="0" alt="feedbacks" src="/images/feedbacks.png"/>
</a>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-1919557-2");
pageTracker._trackPageview();
</script>
</div>
  </body>
</html>
